title: Srilekha Doosa
logo: /assets/img/tempImageUTkaPN-photoaidcom-cropped.jpg
show_downloads: true
navigation:
   title: LinkedIn
    url: /https://www.linkedin.com/in/srilekha-doosa-6163682b2/


theme: jekyll-theme-minimal 
